### ISSUE TITLE
Update to Gnome 45

### ISSUE THREAD

**Issue by MuffinTime14** [arikw/rx-input-layout-switcher#5]
Hi,

I use Fedora and latest version of Fedora (39) uses Gnome 45
Is there an approximate date when the extension will be updated to Gnome 45?
I really love this extension and always use it

Thanks!

**Comment by arikw** [comment]
Hi, I will update the extension in ~2 days

**Comment by arikw** [comment]
New release available: https://github.com/arikw/rx-input-layout-switcher/releases/tag/v6

**Comment by MuffinTime14** [comment]
> New release available: https://github.com/arikw/rx-input-layout-switcher/releases/tag/v6

Thank you very much!
The new version works perfect :)
